name: Build and Push Docker image

on:
  push:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{ vars.DOCKER_USERNAME }}/docker-action
    steps:
      - 
        name: Checkout the code
        uses: actions/checkout@v4
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build & Push the image
        uses: docker/build-push-action@v6
        with:
          context: docker
          push: true
          tags: |
            $DOCKER_IMAGE_NAME:${{ github.sha }}
            $DOCKER_IMAGE_NAME:latest
            

