name: variables.yml

on:
  workflow_dispatch

jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      -
        name: Create a new variables
        run: echo "VAR_1=var_1" >> $GITHUB_ENV
      -
        name: Print the variable
        run: echo "$VAR_1"
      -
        name: set color
        id: selected-color
        run: echo "SELECTED-COLOR=green" >> $GITHUB_OUTPUT
      -
        name: get color
        env:
          SELECTED_COLOR: ${{ steps.selected-color.outputs.SELECTED-COLOR }}
        run: echo "The selected color is ${{ env.SELECTED_COLOR }}"
